### PR TITLE
Migrate to use v1 API

### LINKED ISSUE #1: fluentd v1 migration path
@cosmo0920 Could you please investigate whether this fluentd plugin supports fluentd v0.14/v1 or not?

### PR DESCRIPTION
**Pull request by cosmo0920**
Fixes #1.

Could you confirm this PR with the following steps in your Fluentd v1 evaluation environment, @takuan-osho?
If you have a question, please let me know.

---

### Confirmation steps with td-agent

```log
$ git clone https://github.com/kikumoto/fluent-plugin-sql_fingerprint
$ git fetch origin pull/2/head:pr-2
$ git checkout pr-2
$ td-agent-gem install bundler
$ bundle install --path vendor/bundle
$ bundle exec rake build
$ td-agent-gem install pkg/fluent-plugin-sql_fingerprint-*.gem
$ td-agent -c YOUR_TD_AGENT_CONF.conf
```

### CODE REVIEW

**Comment by takuan-osho** [comment]
@cosmo0920 According to your advice, I tried to `bundle exec rake build`. However, `rake aborted` error occurred like this.

```
$ which bundle
/opt/td-agent/embedded/bin/bundle

$ bundle install
No entry for terminal type "xterm-256color";
using dumb terminal settings.
Using rake 12.3.0
Using cool.io 1.5.3
Using dig_rb 1.0.1
Using http_parser.rb 0.6.0
Using msgpack 1.2.4
Using sigdump 0.2.4
Using strptime 0.2.3
Using thread_safe 0.3.6
Using yajl-ruby 1.3.1
Using power_assert 1.1.1
Using bundler 1.14.5
Using serverengine 2.0.6
Using tzinfo 1.2.5
Using test-unit 3.2.7
Using tzinfo-data 1.2018.3
Using fluentd 1.1.1
Using fluent-plugin-sql_fingerprint 0.0.1 from source at `.`
Bundle complete! 4 Gemfile dependencies, 17 gems now installed.
Bundled gems are installed into ./vendor/bundle.

$ bundle exec rake build
No entry for terminal type "xterm-256color";
using dumb terminal settings.
rake aborted!
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/spec_set.rb:87:in `materialize': Could not find rake-12.3.0 in any of the sources (Bundler::GemNotFound)
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/spec_set.rb:80:in `map!'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/spec_set.rb:80:in `materialize'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/definition.rb:176:in `specs'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/definition.rb:235:in `specs_for'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/definition.rb:224:in `requested_specs'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:118:in `send'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:118:in `requested_specs'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:19:in `setup'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler.rb:100:in `setup'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/setup.rb:20
/home/vagrant/fluent-plugin-sql_fingerprint/vendor/bundle/ruby/2.1.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/opt/td-agent/embedded/bin/bundle:23:in `load'
/opt/td-agent/embedded/bin/bundle:23:in `<main>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

Please tell me how to remove the error. I'm not familiar with ruby or fluentd.

**Comment by cosmo0920** [comment]
It's your homework, though. ;)


Just joking.

[fluent-plugin-sql_fingerprint-0.0.1.gem.zip](https://github.com/kikumoto/fluent-plugin-sql_fingerprint/files/1810508/fluent-plugin-sql_fingerprint-0.0.1.gem.zip)

Using above zipped gem can work in your environment, @takuan-osho ?

**Comment by takuan-osho** [comment]
@cosmo0920 Thank you for your kindness. I will use zipped gem in my environment.

**Comment by takuan-osho** [comment]
@cosmo0920 I confirmed that this PR with your steps in my fluentd v1 environment works well.

**Comment by cosmo0920** [comment]
@kikumoto Could you take a look this PR?

If you will merge and release this gem, please bump up version to v0.1.0 due to bundler updating version management.

@takuan-osho Awesome. Thank you for confirming these patches.

**Comment by cosmo0920** [comment]
Or, you don't have enough time to maintain this plugin, we want to take over this project in @fluent-plugins-nursery.

**Comment by kikumoto** [comment]
@cosmo0920 
Thank you for your PR.
I have merged.
I will release new gem soon.

**Pull request merged**
